return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.14.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 20,
  tilewidth = 32,
  tileheight = 32,
  nextobjectid = 101,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      name = "Spawn",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "Player",
          shape = "ellipse",
          x = 312,
          y = 269,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 103,
          y = 99,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 125,
          y = 48,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 84,
          y = 58,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "Warrior",
          shape = "ellipse",
          x = -9,
          y = 466,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 513,
          y = 63,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 538,
          y = 84,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 536,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 489,
          y = 375,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 487,
          y = 406,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 659,
          y = 33,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 677,
          y = 50,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 54,
          y = 351,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 73,
          y = 370,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 87,
          y = 389,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 92,
          y = 472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 134,
          y = 526,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 227,
          y = 226,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = -49,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 652,
          y = 533,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "Sinistar",
          shape = "ellipse",
          x = 317,
          y = 494,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "Warrior",
          shape = "ellipse",
          x = 9,
          y = 517,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "Warrior",
          shape = "ellipse",
          x = 590,
          y = 38,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 7,
          y = 37,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 28,
          y = 74,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 581,
          y = 88,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 616,
          y = 63,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 672,
          y = 505,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 635,
          y = 495,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 607,
          y = 110,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 526,
          y = 396,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 299,
          y = 521,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "Warrior",
          shape = "ellipse",
          x = 338,
          y = 524,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "Warrior",
          shape = "ellipse",
          x = 368,
          y = 533,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "Warrior",
          shape = "ellipse",
          x = 664,
          y = 464,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "Warrior",
          shape = "ellipse",
          x = 581,
          y = 127,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "Warrior",
          shape = "ellipse",
          x = 139,
          y = 79,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 18,
          y = 227,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 120,
          y = 260,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 170,
          y = 492,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 190,
          y = 468,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 617,
          y = 256,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 602,
          y = 237,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 554,
          y = 396,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 534,
          y = 499,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 404,
          y = 475,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 259,
          y = 373,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 277,
          y = 382,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 345,
          y = 67,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 535,
          y = 195,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 392,
          y = 305,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 294,
          y = 170,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 223,
          y = 277,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 192,
          y = 300,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 121,
          y = 143,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 456,
          y = 150,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 501,
          y = 280,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 388,
          y = 411,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 201,
          y = 390,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = -20,
          y = 301,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = -27,
          y = 321,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 3,
          y = 178,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = -50,
          y = 519,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 636,
          y = 398,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 699,
          y = 289,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 176,
          y = 7,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 211,
          y = 28,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 386,
          y = 12,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 436,
          y = 171,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 405,
          y = 218,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 267,
          y = 150,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 460,
          y = 538,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = -44,
          y = 476,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 705,
          y = 328,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 309,
          y = 304,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 712,
          y = 156,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 563,
          y = 562,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = -60,
          y = 63,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 156,
          y = 257,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 4,
          y = 390,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 236,
          y = 514,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 450,
          y = 51,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 299,
          y = 47,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "Warrior",
          shape = "ellipse",
          x = 340,
          y = 29,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 568,
          y = 190,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 640,
          y = 233,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 666,
          y = 234,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 650,
          y = 214,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = 661,
          y = 250,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "Warrior",
          shape = "ellipse",
          x = -52,
          y = 292,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 132,
          y = 219,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = -28,
          y = 265,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "Worker",
          shape = "ellipse",
          x = -61,
          y = 267,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "Asteroid",
          shape = "ellipse",
          x = 4,
          y = 272,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
