return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 45,
  height = 45,
  tilewidth = 32,
  tileheight = 32,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      name = "Asteroid",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 509,
          y = 1048,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 509,
          y = 1078,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 506,
          y = 1103,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 506,
          y = 1124,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 506,
          y = 1150,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 529,
          y = 1151,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 551,
          y = 1153,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 572,
          y = 1157,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 595,
          y = 1155,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 619,
          y = 1152,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 622,
          y = 1127,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 622,
          y = 1100,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 622,
          y = 1074,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 618,
          y = 1045,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 527,
          y = 1038,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 552,
          y = 1045,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 573,
          y = 1042,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 593,
          y = 1042,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 693,
          y = 803,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 677,
          y = 820,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 664,
          y = 835,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 653,
          y = 847,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 640,
          y = 858,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 630,
          y = 876,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 645,
          y = 883,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 662,
          y = 889,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 681,
          y = 895,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 702,
          y = 899,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 721,
          y = 903,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 706,
          y = 819,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 711,
          y = 837,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 716,
          y = 858,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 720,
          y = 878,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 924,
          y = 945,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 904,
          y = 950,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 888,
          y = 963,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 875,
          y = 978,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 864,
          y = 999,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 862,
          y = 1020,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 865,
          y = 1047,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 872,
          y = 1066,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 886,
          y = 1080,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 904,
          y = 1089,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 923,
          y = 1094,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 942,
          y = 1091,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 970,
          y = 1085,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 949,
          y = 948,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 968,
          y = 955,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 984,
          y = 974,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 990,
          y = 993,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 996,
          y = 1012,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 996,
          y = 1032,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 992,
          y = 1051,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 983,
          y = 1066,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1064,
          y = 597,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1041,
          y = 617,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1029,
          y = 639,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1020,
          y = 655,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1015,
          y = 682,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1004,
          y = 703,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 999,
          y = 727,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 991,
          y = 752,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 978,
          y = 770,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 962,
          y = 784,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 943,
          y = 799,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 927,
          y = 822,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 926,
          y = 847,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 924,
          y = 870,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 930,
          y = 891,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 957,
          y = 908,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 979,
          y = 912,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1000,
          y = 918,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1017,
          y = 938,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1035,
          y = 960,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1048,
          y = 981,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1056,
          y = 1002,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1072,
          y = 1022,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1091,
          y = 1040,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1096,
          y = 1059,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1107,
          y = 1079,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1119,
          y = 1096,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1126,
          y = 1117,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1008,
          y = 375,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 997,
          y = 396,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 989,
          y = 414,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 967,
          y = 424,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 945,
          y = 430,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 924,
          y = 433,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 911,
          y = 448,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 888,
          y = 459,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 879,
          y = 478,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 415,
          y = 221,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 433,
          y = 203,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 461,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 488,
          y = 185,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 518,
          y = 185,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 536,
          y = 168,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 571,
          y = 146,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 404,
          y = 242,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 392,
          y = 302,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 413,
          y = 284,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 430,
          y = 265,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 638,
          y = 113,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 675,
          y = 49,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 206,
          y = 1185,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 233,
          y = 1197,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 253,
          y = 1202,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 272,
          y = 1212,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 294,
          y = 1212,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 310,
          y = 1220,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 328,
          y = 1229,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 351,
          y = 1232,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 377,
          y = 1238,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 396,
          y = 1246,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 415,
          y = 1258,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 434,
          y = 1269,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 448,
          y = 1286,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 456,
          y = 1306,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 462,
          y = 1325,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 471,
          y = 1347,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 479,
          y = 1369,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 494,
          y = 1394,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 507,
          y = 1418,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "Squad",
      visible = false,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 705,
          y = 201,
          width = 0,
          height = 0,
          visible = true,
          properties = {
            ["Warriors"] = "0",
            ["Workers"] = "3"
          }
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1141,
          y = 907,
          width = 0,
          height = 0,
          visible = true,
          properties = {
            ["Warriors"] = "0",
            ["Workers"] = "6"
          }
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 407,
          y = 1206,
          width = 0,
          height = 0,
          visible = true,
          properties = {
            ["Warriors"] = "0",
            ["Workers"] = "2"
          }
        }
      }
    },
    {
      type = "objectgroup",
      name = "Locale",
      visible = false,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "C",
          type = "",
          shape = "ellipse",
          x = 736,
          y = 736,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
