return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 60,
  height = 60,
  tilewidth = 32,
  tileheight = 32,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      name = "Asteroid",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 727,
          y = 836,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 724,
          y = 808,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 732,
          y = 773,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 773,
          y = 760,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 795,
          y = 786,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 807,
          y = 814,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 820,
          y = 837,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 832,
          y = 863,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 724,
          y = 867,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 751,
          y = 816,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 775,
          y = 814,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1200,
          y = 735,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1190,
          y = 767,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1178,
          y = 789,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1170,
          y = 813,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1160,
          y = 843,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1154,
          y = 863,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1173,
          y = 876,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1201,
          y = 884,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1244,
          y = 833,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1214,
          y = 811,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1239,
          y = 804,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1273,
          y = 800,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1280,
          y = 769,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1267,
          y = 740,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1231,
          y = 712,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1201,
          y = 702,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1255,
          y = 728,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1254,
          y = 857,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1230,
          y = 882,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 839,
          y = 1068,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 810,
          y = 1061,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 783,
          y = 1065,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 764,
          y = 1079,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 753,
          y = 1100,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 753,
          y = 1126,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 759,
          y = 1150,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 772,
          y = 1171,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 796,
          y = 1181,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 826,
          y = 1181,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 857,
          y = 1172,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1104,
          y = 1031,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1100,
          y = 1051,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1098,
          y = 1069,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1094,
          y = 1085,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1088,
          y = 1111,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1085,
          y = 1130,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1078,
          y = 1155,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1069,
          y = 1176,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1093,
          y = 1182,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1117,
          y = 1180,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1141,
          y = 1173,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1166,
          y = 1157,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1186,
          y = 1133,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1127,
          y = 1026,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1145,
          y = 1042,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1166,
          y = 1055,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1175,
          y = 1078,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1185,
          y = 1104,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 748,
          y = 739,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 721,
          y = 888,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "Squad",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 957,
          y = 692,
          width = 0,
          height = 0,
          visible = true,
          properties = {
            ["Warriors"] = "3",
            ["Workers"] = "3"
          }
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 1130,
          y = 1115,
          width = 0,
          height = 0,
          visible = true,
          properties = {
            ["Warriors"] = "1",
            ["Workers"] = "6"
          }
        },
        {
          name = "",
          type = "",
          shape = "ellipse",
          x = 583,
          y = 1313,
          width = 0,
          height = 0,
          visible = true,
          properties = {
            ["Warriors"] = "3",
            ["Workers"] = "2"
          }
        }
      }
    },
    {
      type = "objectgroup",
      name = "Locale",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "BR",
          type = "",
          shape = "ellipse",
          x = 1920,
          y = 1920,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "B",
          type = "",
          shape = "ellipse",
          x = 960,
          y = 1920,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "BL",
          type = "",
          shape = "ellipse",
          x = 0,
          y = 1920,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "TL",
          type = "",
          shape = "ellipse",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "TR",
          type = "",
          shape = "ellipse",
          x = 1920,
          y = 0,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "T",
          type = "",
          shape = "ellipse",
          x = 960,
          y = 0,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "C",
          type = "",
          shape = "ellipse",
          x = 960,
          y = 960,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "R",
          type = "",
          shape = "ellipse",
          x = 1920,
          y = 960,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "L",
          type = "",
          shape = "ellipse",
          x = 0,
          y = 960,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
